spring:
  datasource:
    username: root
    password: srapa101
    url: jdbc:mysql://localhost:3306/pizzeria?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT:${SERVER_PORT:0}} # randomowy